package com.example.util

object Translator {

    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "MD3 calc",
            "calculator" to "Calculator",
            "converter" to "Converter",
            "bmi" to "BMI",
            "date_calc" to "Date Calc",
            "settings" to "Settings",
            "history" to "History",
            "clear_all" to "Clear All",
            "empty_history" to "No History Records Yet",
            "empty_history_desc" to "Perform calculations, conversions, or BMI checks to see them here.",
            "theme" to "Theme",
            "theme_light" to "Light",
            "theme_dark" to "Dark",
            "theme_system" to "System",
            "language" to "Language",
            "bmi_weight" to "Weight",
            "bmi_height" to "Height",
            "bmi_calculate" to "Calculate BMI",
            "bmi_result" to "Your BMI is",
            "bmi_category" to "Category",
            "bmi_underweight" to "Underweight",
            "bmi_normal" to "Normal Weight",
            "bmi_overweight" to "Overweight",
            "bmi_obese" to "Obese",
            "bmi_advice" to "Advice",
            "date_start" to "Start Date",
            "date_end" to "End Date",
            "date_diff_days" to "Total Days",
            "date_diff_weeks" to "Total Weeks",
            "date_diff_detailed" to "Detailed difference",
            "date_calculate" to "Calculate Interval",
            "eng_mode" to "Scientific Mode",
            "std_mode" to "Standard Mode",
            "ask_gemini" to "Ask Gemini",
            "rate_sync" to "Sync Rates",
            "currency" to "Currency",
            "length" to "Length",
            "temperature" to "Temperature",
            "weight" to "Weight/Mass",
            "area" to "Area",
            "volume" to "Volume",
            "data_storage" to "Data / Storage",
            "number_systems" to "Number Systems",
            "ai_translator" to "AI Smart Translator",
            "tools" to "Tools",
            "time" to "Time",
            "speed" to "Speed",
            "pressure" to "Pressure",
            "energy" to "Energy",
            "bmi_desc" to "Personal Body Mass Index calculator",
            "bmi_metric" to "Metric (kg/cm)",
            "bmi_imperial" to "Imperial (lbs/inch)",
            "date_calc_desc" to "Calculate duration between dates easily",
            "date_results" to "Duration Results",
            "ok" to "OK",
            "cancel" to "Cancel",
            "ai_translator_desc" to "Ask Gemini to translate any complex units, currencies, or mathematical questions in plain text.",
            "ai_prompt_placeholder" to "E.g., How many Megabits in 50 Megabytes, and how is it calculated?",
            "clear" to "Clear",
            "ai_result_title" to "AI Translation Result",
            "weeks" to "weeks",
            "days" to "days",
            "months" to "months",
            "years" to "years",
            "interval_desc" to "Interval",
            "bmi_check_desc" to "BMI Check",
            "unit_lbs" to "lbs",
            "unit_inches" to "inches",
            "unit_kg" to "kg",
            "unit_cm" to "cm",
            "from_unit" to "From Unit",
            "to_unit" to "To Unit",
            "save_to_history" to "Save to History",
            "to" to "to"
        ),
        "ru" to mapOf(
            "app_name" to "MD3 калькулятор",
            "calculator" to "Калькулятор",
            "converter" to "Конвертер",
            "bmi" to "ИМТ",
            "date_calc" to "Счётчик дат",
            "settings" to "Настройки",
            "history" to "История",
            "clear_all" to "Очистить всё",
            "empty_history" to "История пуста",
            "empty_history_desc" to "Выполните расчёты, конвертации или проверку ИМТ, чтобы они появились здесь.",
            "theme" to "Тема оформления",
            "theme_light" to "Светлая",
            "theme_dark" to "Тёмная",
            "theme_system" to "Системная",
            "language" to "Язык приложения",
            "bmi_weight" to "Вес",
            "bmi_height" to "Рост",
            "bmi_calculate" to "Рассчитать ИМТ",
            "bmi_result" to "Ваш ИМТ равен",
            "bmi_category" to "Категория",
            "bmi_underweight" to "Дефицит веса",
            "bmi_normal" to "Нормальный вес",
            "bmi_overweight" to "Избыточный вес",
            "bmi_obese" to "Ожирение",
            "bmi_advice" to "Совет",
            "date_start" to "Начальная дата",
            "date_end" to "Конечная дата",
            "date_diff_days" to "Всего дней",
            "date_diff_weeks" to "Всего недель",
            "date_diff_detailed" to "Детальная разница",
            "date_calculate" to "Вычислить интервал",
            "eng_mode" to "Инженерный",
            "std_mode" to "Обычный",
            "ask_gemini" to "Спросить Gemini",
            "rate_sync" to "Обновить курсы",
            "currency" to "Валюта",
            "length" to "Длина",
            "temperature" to "Температура",
            "weight" to "Вес и масса",
            "area" to "Площадь",
            "volume" to "Объём",
            "data_storage" to "Типы памяти",
            "number_systems" to "Системы счисления",
            "ai_translator" to "AI Умный переводчик",
            "tools" to "Инструменты",
            "time" to "Время",
            "speed" to "Скорость",
            "pressure" to "Давление",
            "energy" to "Энергия",
            "bmi_desc" to "Индивидуальный расчёт индекса массы тела",
            "bmi_metric" to "Метрическая (кг/см)",
            "bmi_imperial" to "Имперская (фунты/дюймы)",
            "date_calc_desc" to "Калькулятор интервалов времени между датами",
            "date_results" to "Результаты расчёта",
            "ok" to "ОК",
            "cancel" to "Отмена",
            "ai_translator_desc" to "Задайте Gemini любой сложный вопрос о переводе величин, валют или математических расчётах.",
            "ai_prompt_placeholder" to "Например: Сколько мегабит в 50 мегабайтах и как это рассчитывается?",
            "clear" to "Сброс",
            "ai_result_title" to "Ответ искусственного интеллекта",
            "weeks" to "недель",
            "days" to "дней",
            "months" to "месяцев",
            "years" to "лет",
            "interval_desc" to "Интервал",
            "bmi_check_desc" to "Расчёт ИМТ",
            "unit_lbs" to "фунты",
            "unit_inches" to "дюймы",
            "unit_kg" to "кг",
            "unit_cm" to "см",
            "from_unit" to "Исходная единица",
            "to_unit" to "Целевая единица",
            "save_to_history" to "Сохранить в историю",
            "to" to "в"
        ),
        "uk" to mapOf(
            "app_name" to "MD3 Калькулятор",
            "calculator" to "Калькулятор",
            "converter" to "Конвертер",
            "bmi" to "ІМТ",
            "date_calc" to "Лічильник дат",
            "settings" to "Налаштування",
            "history" to "Історія",
            "clear_all" to "Очистити все",
            "empty_history" to "Історія порожня",
            "empty_history_desc" to "Виконайте розрахунки, конвертації або перевірку ІМТ, щоб вони з\'явилися тут.",
            "theme" to "Тема оформлення",
            "theme_light" to "Світла",
            "theme_dark" to "Темна",
            "theme_system" to "Синизна",
            "language" to "Мова додатка",
            "bmi_weight" to "Вага",
            "bmi_height" to "Зріст",
            "bmi_calculate" to "Розрахувати ІМТ",
            "bmi_result" to "Ваш ІМТ дорівнює",
            "bmi_category" to "Категорія",
            "bmi_underweight" to "Дефіцит ваги",
            "bmi_normal" to "Нормальна вага",
            "bmi_overweight" to "Надмірна вага",
            "bmi_obese" to "Ожиріння",
            "bmi_advice" to "Порада",
            "date_start" to "Початкова дата",
            "date_end" to "Кінцева дата",
            "date_diff_days" to "Всього днів",
            "date_diff_weeks" to "Всього тижнів",
            "date_diff_detailed" to "Детальна різниця",
            "date_calculate" to "Обчислити інтервал",
            "eng_mode" to "Інженерний",
            "std_mode" to "Звичайний",
            "ask_gemini" to "Запитати Gemini",
            "rate_sync" to "Оновити курси",
            "currency" to "Валюта",
            "length" to "Довжина",
            "temperature" to "Температура",
            "weight" to "Вага та маса",
            "area" to "Площа",
            "volume" to "Об\'єм",
            "data_storage" to "Типи пам\'яті",
            "number_systems" to "Системи числення",
            "ai_translator" to "AI Розумний перекладач",
            "tools" to "Інструменти",
            "time" to "Час",
            "speed" to "Швидкість",
            "pressure" to "Тиск",
            "energy" to "Енергія",
            "bmi_desc" to "Індивідуальний розрахунок індексу маси тіла",
            "bmi_metric" to "Метрична (кг/см)",
            "bmi_imperial" to "Імперська (фунти/дюйми)",
            "date_calc_desc" to "Калькулятор інтервалів часу між датами",
            "date_results" to "Результати розрахунку",
            "ok" to "ОК",
            "cancel" to "Скасувати",
            "ai_translator_desc" to "Задайте Gemini будь-яке складне питання про переведення величин, валют або математичні розрахунки.",
            "ai_prompt_placeholder" to "Наприклад: Скільки мегабіт у 50 мегабайтах і як це розраховується?",
            "clear" to "Скинути",
            "ai_result_title" to "Відповідь штучного інтелекту",
            "weeks" to "тижнів",
            "days" to "днів",
            "months" to "місяців",
            "years" to "років",
            "interval_desc" to "Інтервал",
            "bmi_check_desc" to "Розрахунок ІМТ",
            "unit_lbs" to "фунти",
            "unit_inches" to "дюйми",
            "unit_kg" to "кг",
            "unit_cm" to "см",
            "from_unit" to "Вихідна одиниця",
            "to_unit" to "Цільова одиниця",
            "save_to_history" to "Зберегти в історію",
            "to" to "в"
        ),
        "be" to mapOf(
            "app_name" to "MD3 Калькулятар",
            "calculator" to "Калькулятар",
            "converter" to "Канвертар",
            "bmi" to "ІМТ",
            "date_calc" to "Лічыльнік дат",
            "settings" to "Налады",
            "history" to "Гісторыя",
            "clear_all" to "Ачысціць усё",
            "empty_history" to "Гісторыя пустая",
            "empty_history_desc" to "Выканайце разлікі, канвертацыі або праверку ІМТ, каб яны з\'явіліся тут.",
            "theme" to "Тэма афармлення",
            "theme_light" to "Светлая",
            "theme_dark" to "Цёмная",
            "theme_system" to "Сістэмная",
            "language" to "Мова прыкладання",
            "bmi_weight" to "Вага",
            "bmi_height" to "Рост",
            "bmi_calculate" to "Разлічыць ІМТ",
            "bmi_result" to "Ваш ІМТ роўны",
            "bmi_category" to "Катэгорыя",
            "bmi_underweight" to "Дэфіцыт вагі",
            "bmi_normal" to "Нармальная вага",
            "bmi_overweight" to "Лішняя вага",
            "bmi_obese" to "Абтыўная вага",
            "bmi_advice" to "Парада",
            "date_start" to "Пачатковая дата",
            "date_end" to "Канчатковая дата",
            "date_diff_days" to "Усяго дзён",
            "date_diff_weeks" to "Усяго тыдняў",
            "date_diff_detailed" to "Дэталёвая розніца",
            "date_calculate" to "Вылічыць інтэрвал",
            "eng_mode" to "Інжынерны",
            "std_mode" to "Звычайны",
            "ask_gemini" to "Спытаць Gemini",
            "rate_sync" to "Абнавіць курсы",
            "currency" to "Валюта",
            "length" to "Даўжыня",
            "temperature" to "Тэмпература",
            "weight" to "Вага і маса",
            "area" to "Плошча",
            "volume" to "Аб\'ём",
            "data_storage" to "Тыпы памяці",
            "number_systems" to "Сістэмы злічэння",
            "ai_translator" to "AI Разумны перакладчык",
            "tools" to "Інструменты",
            "time" to "Час",
            "speed" to "Хуткасць",
            "pressure" to "Ціск",
            "energy" to "Энергія",
            "bmi_desc" to "Індывідуальны разлік індэкса масы цела",
            "bmi_metric" to "Метрычная (кг/см)",
            "bmi_imperial" to "Імперская (фунты/цалі)",
            "date_calc_desc" to "Калькулятар інтэрвалаў часу паміж датамі",
            "date_results" to "Вынікі разліку",
            "ok" to "ОК",
            "cancel" to "Адмена",
            "ai_translator_desc" to "Задайте Gemini любое складанае пытанне пра перавод велічынь, валют або матэматычныя разлікі.",
            "ai_prompt_placeholder" to "Напрыклад: Колькі мегабіт у 50 мегабайтах і як гэта разлічваецца?",
            "clear" to "Скінуць",
            "ai_result_title" to "Адказ штучнага інтэлекту",
            "weeks" to "тыдняў",
            "days" to "дзён",
            "months" to "месяцаў",
            "years" to "гадоў",
            "interval_desc" to "Інтэрвал",
            "bmi_check_desc" to "Разлік ІМТ",
            "unit_lbs" to "фунты",
            "unit_inches" to "цалі",
            "unit_kg" to "кг",
            "unit_cm" to "см",
            "from_unit" to "Зыходная адзінка",
            "to_unit" to "Мэтавая адзінка",
            "save_to_history" to "Захаваць у гісторыю",
            "to" to "у"
        ),
        "kk" to mapOf(
            "app_name" to "MD3 Калькулятор",
            "calculator" to "Калькулятор",
            "converter" to "Конвертер",
            "bmi" to "ИМТ",
            "date_calc" to "Күн санауыш",
            "settings" to "Баптаулар",
            "history" to "Тарих",
            "clear_all" to "Барлығын тазалау",
            "empty_history" to "Тарих бос",
            "empty_history_desc" to "Мұнда көру үшін есептеулер, конверсиялар немесе ИМТ тексерулерін орындаңыз.",
            "theme" to "Безендіру тақырыбы",
            "theme_light" to "Жарық",
            "theme_dark" to "Қараңғы",
            "theme_system" to "Жүйелік",
            "language" to "Қолданба тілі",
            "bmi_weight" to "Салмақ",
            "bmi_height" to "Бой",
            "bmi_calculate" to "ИМТ есептеу",
            "bmi_result" to "Сіздің ИМТ",
            "bmi_category" to "Санат",
            "bmi_underweight" to "Салмақ жеткіліксіздігі",
            "bmi_normal" to "Қалыпты салмақ",
            "bmi_overweight" to "Артық салмақ",
            "bmi_obese" to "Семіздік",
            "bmi_advice" to "Кеңес",
            "date_start" to "Бастапқы күн",
            "date_end" to "Соңғы күн",
            "date_diff_days" to "Барлық күндер",
            "date_diff_weeks" to "Барлық апталар",
            "date_diff_detailed" to "Толық айырмашылық",
            "date_calculate" to "Аралықты есептеу",
            "eng_mode" to "Инженерлік",
            "std_mode" to "Қарапайым",
            "ask_gemini" to "Gemini-ден сұрау",
            "rate_sync" to "Бағамдарды жаңарту",
            "currency" to "Валюта",
            "length" to "Ұзындық",
            "temperature" to "Температура",
            "weight" to "Салмақ пен масса",
            "area" to "Аудан",
            "volume" to "Көлем",
            "data_storage" to "Жад типтері",
            "number_systems" to "Санау жүйелері",
            "ai_translator" to "AI Ақылды аудармашы",
            "tools" to "Құралдар",
            "time" to "Уақыт",
            "speed" to "Жылдамдық",
            "pressure" to "Қысым",
            "energy" to "Энергия",
            "bmi_desc" to "Дене массасының индексін жеке есептеу",
            "bmi_metric" to "Метрикалық (кг/см)",
            "bmi_imperial" to "Империялық (фунт/дюйм)",
            "date_calc_desc" to "Күндер арасындағы уақыт аралығын есептеу",
            "date_results" to "Есептеу нәтижелері",
            "ok" to "ОК",
            "cancel" to "Бас тарту",
            "ai_translator_desc" to "Gemini-ге шамаларды, валюталарды немесе математикалық есептеулерді аудару туралы кез келген күрделі сұрақ қойыңыз.",
            "ai_prompt_placeholder" to "Мысалы: 50 мегабайтта қанша мегабит бар және ол қалай есептеледі?",
            "clear" to "Тазарту",
            "ai_result_title" to "Жасанды интеллект жауабы",
            "weeks" to "апта",
            "days" to "күн",
            "months" to "ай",
            "years" to "жыл",
            "interval_desc" to "Аралық",
            "bmi_check_desc" to "ИМТ есептеу",
            "unit_lbs" to "фунт",
            "unit_inches" to "дюйм",
            "unit_kg" to "кг",
            "unit_cm" to "см",
            "from_unit" to "Бастапқы өлшем",
            "to_unit" to "Мақсатты өлшем",
            "save_to_history" to "Тарихқа сақтау",
            "to" to "->"
        ),
        "es" to mapOf(
            "app_name" to "Calculadora MD3",
            "calculator" to "Calculadora",
            "converter" to "Conversor",
            "bmi" to "IMC",
            "date_calc" to "Cálculo de Fechas",
            "settings" to "Ajustes",
            "history" to "Historial",
            "clear_all" to "Borrar Todo",
            "empty_history" to "Sin Historial Aún",
            "empty_history_desc" to "Realice cálculos, conversiones o IMC para verlos aquí.",
            "theme" to "Tema",
            "theme_light" to "Claro",
            "theme_dark" to "Oscuro",
            "theme_system" to "Sistema",
            "language" to "Idioma",
            "bmi_weight" to "Peso",
            "bmi_height" to "Altura",
            "bmi_calculate" to "Calcular IMC",
            "bmi_result" to "Su IMC es",
            "bmi_category" to "Categoría",
            "bmi_underweight" to "Bajo peso",
            "bmi_normal" to "Peso normal",
            "bmi_overweight" to "Sobrepeso",
            "bmi_obese" to "Obesidad",
            "bmi_advice" to "Consejo",
            "date_start" to "Fecha Inicio",
            "date_end" to "Fecha Fin",
            "date_diff_days" to "Días Totales",
            "date_diff_weeks" to "Semanas Totales",
            "date_diff_detailed" to "Diferencia detallada",
            "date_calculate" to "Calcular Intervalo",
            "eng_mode" to "Modo Científico",
            "std_mode" to "Modo Estándar",
            "ask_gemini" to "Preguntar a Gemini",
            "rate_sync" to "Sincronizar Tasas",
            "currency" to "Moneda",
            "length" to "Longitud",
            "temperature" to "Temperatura",
            "weight" to "Peso/Masa",
            "area" to "Área",
            "volume" to "Volumen",
            "data_storage" to "Datos / Almacenamiento",
            "number_systems" to "Sistemas Numéricos",
            "ai_translator" to "Traductor Inteligente AI",
            "tools" to "Herramientas",
            "time" to "Tiempo",
            "speed" to "Velocidad",
            "pressure" to "Presión",
            "energy" to "Energía",
            "bmi_desc" to "Calculadora de índice de masa corporal personal",
            "bmi_metric" to "Métrica (kg/cm)",
            "bmi_imperial" to "Imperial (lbs/pulgadas)",
            "date_calc_desc" to "Calcular la duración entre fechas fácilmente",
            "date_results" to "Resultados de la Duración",
            "ok" to "Aceptar",
            "cancel" to "Cancelar",
            "ai_translator_desc" to "Pregúntele a Gemini sobre cualquier conversión compleja de unidades, monedas o cálculos matemáticos en texto plano.",
            "ai_prompt_placeholder" to "Ej., ¿Cuántos Megabits hay en 50 Megabytes y cómo se calcula?",
            "clear" to "Borrar",
            "ai_result_title" to "Resultado de Traducción AI",
            "weeks" to "semanas",
            "days" to "días",
            "months" to "meses",
            "years" to "años",
            "interval_desc" to "Intervalo",
            "bmi_check_desc" to "Verificación de IMC",
            "unit_lbs" to "lbs",
            "unit_inches" to "pulgadas",
            "unit_kg" to "kg",
            "unit_cm" to "cm",
            "from_unit" to "Unidad de origen",
            "to_unit" to "Unidad de destino",
            "save_to_history" to "Guardar en el historial",
            "to" to "a"
        ),
        "pl" to mapOf(
            "app_name" to "Kalkulator MD3",
            "calculator" to "Kalkulator",
            "converter" to "Konwerter",
            "bmi" to "BMI",
            "date_calc" to "Kalkulator Dat",
            "settings" to "Ustawienia",
            "history" to "Historia",
            "clear_all" to "Wyczyść Wszystko",
            "empty_history" to "Brak Historii",
            "empty_history_desc" to "Wykonaj obliczenia, konwersje lub sprawdź BMI, aby zobaczyć je tutaj.",
            "theme" to "Motyw",
            "theme_light" to "Jasny",
            "theme_dark" to "Ciemny",
            "theme_system" to "Systemowy",
            "language" to "Język",
            "bmi_weight" to "Waga",
            "bmi_height" to "Wzrost",
            "bmi_calculate" to "Oblicz BMI",
            "bmi_result" to "Twoje BMI to",
            "bmi_category" to "Kategoria",
            "bmi_underweight" to "Niedowaga",
            "bmi_normal" to "Waga prawidłowa",
            "bmi_overweight" to "Nadwaga",
            "bmi_obese" to "Otyłość",
            "bmi_advice" to "Rada",
            "date_start" to "Data Początkowa",
            "date_end" to "Data Końcowa",
            "date_diff_days" to "Wszystkich Dni",
            "date_diff_weeks" to "Wszystkich Tygodni",
            "date_diff_detailed" to "Szczegółowa różnica",
            "date_calculate" to "Oblicz Interwał",
            "eng_mode" to "Tryb Naukowy",
            "std_mode" to "Tryb Standardowy",
            "ask_gemini" to "Zapytaj Gemini",
            "rate_sync" to "Synchronizuj Kursy",
            "currency" to "Waluta",
            "length" to "Długość",
            "temperature" to "Temperatura",
            "weight" to "Waga/Masa",
            "area" to "Obszar",
            "volume" to "Objętość",
            "data_storage" to "Pamięć / Dane",
            "number_systems" to "Systemy Liczbowe",
            "ai_translator" to "Inteligentny Tłumacz AI",
            "tools" to "Narzędzia",
            "time" to "Czas",
            "speed" to "Prędkość",
            "pressure" to "Ciśnienie",
            "energy" to "Energia",
            "bmi_desc" to "Indywidualny kalkulator wskaźnika masy ciała",
            "bmi_metric" to "Metryczny (kg/cm)",
            "bmi_imperial" to "Imperialny (lbs/cale)",
            "date_calc_desc" to "Łatwo oblicz czas między datami",
            "date_results" to "Wyniki Obliczeń",
            "ok" to "OK",
            "cancel" to "Anuluj",
            "ai_translator_desc" to "Zapytaj Gemini o dowolne złożone jednostki, waluty lub obliczenia matematyczne w prostym tekście.",
            "ai_prompt_placeholder" to "Np. Ile megabitów jest w 50 megabajtach i jak to się oblicza?",
            "clear" to "Wyczyść",
            "ai_result_title" to "Wynik Tłumaczenia AI",
            "weeks" to "tygodni",
            "days" to "dni",
            "months" to "miesięcy",
            "years" to "lat",
            "interval_desc" to "Przedział",
            "bmi_check_desc" to "Sprawdzenie BMI",
            "unit_lbs" to "lbs",
            "unit_inches" to "cale",
            "unit_kg" to "kg",
            "unit_cm" to "cm",
            "from_unit" to "Jednostka początkowa",
            "to_unit" to "Jednostka docelowa",
            "save_to_history" to "Zapisz w historii",
            "to" to "na"
        ),
        "de" to mapOf(
            "app_name" to "MD3 Rechner",
            "calculator" to "Rechner",
            "converter" to "Konverter",
            "bmi" to "BMI",
            "date_calc" to "Datumsrechner",
            "settings" to "Einstellungen",
            "history" to "Verlauf",
            "clear_all" to "Alles Löschen",
            "empty_history" to "Noch kein Verlauf",
            "empty_history_desc" to "Führen Sie Berechnungen, Konvertierungen oder BMI-Checks durch, um sie hier zu sehen.",
            "theme" to "Thema",
            "theme_light" to "Hell",
            "theme_dark" to "Dunkel",
            "theme_system" to "System",
            "language" to "Sprache",
            "bmi_weight" to "Gewicht",
            "bmi_height" to "Größe",
            "bmi_calculate" to "BMI Berechnen",
            "bmi_result" to "Ihr BMI ist",
            "bmi_category" to "Kategorie",
            "bmi_underweight" to "Untergewicht",
            "bmi_normal" to "Normalgewicht",
            "bmi_overweight" to "Übergewicht",
            "bmi_obese" to "Adipositas",
            "bmi_advice" to "Tipp",
            "date_start" to "Startdatum",
            "date_end" to "Enddatum",
            "date_diff_days" to "Tage Gesamt",
            "date_diff_weeks" to "Wochen Gesamt",
            "date_diff_detailed" to "Detaillierter Unterschied",
            "date_calculate" to "Intervall Berechnen",
            "eng_mode" to "Wissenschaftlich",
            "std_mode" to "Standard",
            "ask_gemini" to "Gemini Fragen",
            "rate_sync" to "Kurse Abgleichen",
            "currency" to "Währung",
            "length" to "Länge",
            "temperature" to "Temperatur",
            "weight" to "Gewicht/Masse",
            "area" to "Fläche",
            "volume" to "Volumen",
            "data_storage" to "Datenspeicher",
            "number_systems" to "Zahlensysteme",
            "ai_translator" to "AI Smart Übersetzer",
            "tools" to "Werkzeuge",
            "time" to "Zeit",
            "speed" to "Geschwindigkeit",
            "pressure" to "Druck",
            "energy" to "Energie",
            "bmi_desc" to "Persönlicher Body-Mass-Index-Rechner",
            "bmi_metric" to "Metrisch (kg/cm)",
            "bmi_imperial" to "Imperial (lbs/Zoll)",
            "date_calc_desc" to "Berechnen Sie die Dauer zwischen Daten ganz einfach",
            "date_results" to "Ergebnisse der Dauer",
            "ok" to "OK",
            "cancel" to "Abbrechen",
            "ai_translator_desc" to "Fragen Sie Gemini nach komplexen Einheiten, Währungen oder mathematischen Berechnungen im Klartext.",
            "ai_prompt_placeholder" to "Z.B. Wie viele Megabits sind in 50 Megabytes und wie wird das berechnet?",
            "clear" to "Zurücksetzen",
            "ai_result_title" to "AI Übersetzungsergebnis",
            "weeks" to "Wochen",
            "days" to "Tage",
            "months" to "Monate",
            "years" to "Jahre",
            "interval_desc" to "Intervall",
            "bmi_check_desc" to "BMI Überprüfung",
            "unit_lbs" to "lbs",
            "unit_inches" to "Zoll",
            "unit_kg" to "kg",
            "unit_cm" to "cm",
            "from_unit" to "Ausgangseinheit",
            "to_unit" to "Zieleinheit",
            "save_to_history" to "Im Verlauf speichern",
            "to" to "in"
        )
    )

    private val unitTranslations = mapOf(
        "en" to mapOf(
            // Length
            "m" to "meters (m)",
            "km" to "kilometers (km)",
            "cm" to "centimeters (cm)",
            "mm" to "millimeters (mm)",
            "mile" to "miles (mi)",
            "yard" to "yards (yd)",
            "foot" to "feet (ft)",
            "inch" to "inches (in)",
            // Temperature
            "Celsius (°C)" to "Celsius (°C)",
            "Fahrenheit (°F)" to "Fahrenheit (°F)",
            "Kelvin (K)" to "Kelvin (K)",
            // Weight
            "kg" to "kilograms (kg)",
            "g" to "grams (g)",
            "mg" to "milligrams (mg)",
            "µg" to "micrograms (µg)",
            "ton (t)" to "metric tons (t)",
            "carat (ct)" to "carats (ct)",
            "lb" to "pounds (lb)",
            "oz" to "ounces (oz)",
            "stone (st)" to "stones (st)",
            "grain (gr)" to "grains (gr)",
            // Area
            "sq meter (m²)" to "sq meters (m²)",
            "sq km (km²)" to "sq kilometers (km²)",
            "sq mile (mi²)" to "sq miles (mi²)",
            "sq yard (yd²)" to "sq yards (yd²)",
            "sq foot (ft²)" to "sq feet (ft²)",
            "acre" to "acres",
            // Volume
            "liter (L)" to "liters (L)",
            "ml" to "milliliters (ml)",
            "gallon (gal)" to "gallons (gal)",
            "cup" to "cups",
            // Data Storage
            "Bit (b)" to "Bit (b)",
            "Byte (B)" to "Byte (B)",
            "Kilobit (Kb)" to "Kilobit (Kb)",
            "Kilobyte (KB)" to "Kilobyte (KB)",
            "Megabit (Mb)" to "Megabit (Mb)",
            "Megabyte (MB)" to "Megabyte (MB)",
            "Gigabit (Gb)" to "Gigabit (Gb)",
            "Gigabyte (GB)" to "Gigabyte (GB)",
            "Terabit (Tb)" to "Terabit (Tb)",
            "Terabyte (TB)" to "Terabyte (TB)",
            // Number Systems
            "Decimal" to "Decimal",
            "Binary" to "Binary",
            "Hexadecimal" to "Hexadecimal",
            "Octal" to "Octal",
            // Time
            "Second (s)" to "Second (s)",
            "Minute (min)" to "Minute (min)",
            "Hour (h)" to "Hour (h)",
            "Day (d)" to "Day (d)",
            "Week (wk)" to "Week (wk)",
            "Year (yr)" to "Year (yr)",
            // Speed
            "m/s" to "m/s",
            "km/h" to "km/h",
            "mph" to "mph",
            "knots" to "knots",
            // Pressure
            "Pascal (Pa)" to "Pascal (Pa)",
            "Bar (bar)" to "Bar (bar)",
            "Atmosphere (atm)" to "Atmosphere (atm)",
            "psi" to "psi",
            // Energy
            "Joule (J)" to "Joule (J)",
            "Kilojoule (kJ)" to "Kilojoule (kJ)",
            "Calorie (cal)" to "Calorie (cal)",
            "Kilocalorie (kcal)" to "Kilocalorie (kcal)",
            "Watt-hour (Wh)" to "Watt-hour (Wh)",
            "Kilowatt-hour (kWh)" to "Kilowatt-hour (kWh)"
        ),
        "ru" to mapOf(
            // Length
            "m" to "метры (м)",
            "km" to "километры (км)",
            "cm" to "сантиметры (см)",
            "mm" to "миллиметры (мм)",
            "mile" to "мили (ми)",
            "yard" to "ярды (ярд)",
            "foot" to "футы (фт)",
            "inch" to "дюймы (дй)",
            // Temperature
            "Celsius (°C)" to "Градус Цельсия (°C)",
            "Fahrenheit (°F)" to "Градус Фаренгейта (°F)",
            "Kelvin (K)" to "Кельвин (K)",
            // Weight
            "kg" to "килограммы (кг)",
            "g" to "граммы (г)",
            "mg" to "миллиграммы (мг)",
            "µg" to "микрограммы (мкг)",
            "ton (t)" to "тонны (т)",
            "carat (ct)" to "караты (кар)",
            "lb" to "фунты (фнт)",
            "oz" to "унции (унц)",
            "stone (st)" to "стоуны (ст)",
            "grain (gr)" to "граны (гр)",
            // Area
            "sq meter (m²)" to "кв. метры (м²)",
            "sq km (km²)" to "кв. километры (км²)",
            "sq mile (mi²)" to "кв. мили (ми²)",
            "sq yard (yd²)" to "кв. ярды (ярд²)",
            "sq foot (ft²)" to "кв. футы (фт²)",
            "acre" to "акры",
            // Volume
            "liter (L)" to "литры (л)",
            "ml" to "миллилитры (мл)",
            "gallon (gal)" to "галлоны (гал)",
            "cup" to "чашки",
            // Data Storage
            "Bit (b)" to "Бит (б)",
            "Byte (B)" to "Байт (Б)",
            "Kilobit (Kb)" to "Килобит (Кб)",
            "Kilobyte (KB)" to "Килобайт (КБ)",
            "Megabit (Mb)" to "Мегабит (Мб)",
            "Megabyte (MB)" to "Megabyte (МБ)",
            "Gigabit (Gb)" to "Гигабит (Гб)",
            "Gigabyte (GB)" to "Гигабайт (ГБ)",
            "Terabit (Tb)" to "Терабит (Тб)",
            "Terabyte (TB)" to "Терабайт (ТБ)",
            // Number Systems
            "Decimal" to "Десятичная",
            "Binary" to "Двоичная",
            "Hexadecimal" to "Шестнадцатеричная",
            "Octal" to "Восьмеричная",
            // Time
            "Second (s)" to "Секунда (с)",
            "Minute (min)" to "Минута (мин)",
            "Hour (h)" to "Час (ч)",
            "Day (d)" to "День (дн)",
            "Week (wk)" to "Неделя (нед)",
            "Year (yr)" to "Год (г)",
            // Speed
            "m/s" to "м/с",
            "km/h" to "км/ч",
            "mph" to "миль/ч",
            "knots" to "узлы",
            // Pressure
            "Pascal (Pa)" to "Паскаль (Па)",
            "Bar (bar)" to "Бар (бар)",
            "Atmosphere (atm)" to "Атмосфера (атм)",
            "psi" to "psi",
            // Energy
            "Joule (J)" to "Джоуль (Дж)",
            "Kilojoule (kJ)" to "Килоджоуль (кДж)",
            "Calorie (cal)" to "Калория (кал)",
            "Kilocalorie (kcal)" to "Килокалория (ккал)",
            "Watt-hour (Wh)" to "Ватт-час (Вт·ч)",
            "Kilowatt-hour (kWh)" to "Киловатт-час (кВт·ч)"
        ),
        "uk" to mapOf(
            // Length
            "m" to "метри (м)",
            "km" to "кілометри (км)",
            "cm" to "сантиметри (см)",
            "mm" to "міліметри (мм)",
            "mile" to "милі (ми)",
            "yard" to "ярди (ярд)",
            "foot" to "фути (фт)",
            "inch" to "дюйми (дй)",
            // Temperature
            "Celsius (°C)" to "Градус Цельсія (°C)",
            "Fahrenheit (°F)" to "Градус Фаренгейта (°F)",
            "Kelvin (K)" to "Кельвін (K)",
            // Weight
            "kg" to "кілограми (кг)",
            "g" to "грами (г)",
            "mg" to "міліграми (мг)",
            "µg" to "мікрограми (мкг)",
            "ton (t)" to "тонни (т)",
            "carat (ct)" to "карати (кар)",
            "lb" to "фунти (фнт)",
            "oz" to "унції (унц)",
            "stone (st)" to "стоуни (ст)",
            "grain (gr)" to "грани (гр)",
            // Area
            "sq meter (m²)" to "кв. метри (м²)",
            "sq km (km²)" to "кв. кілометри (км²)",
            "sq mile (mi²)" to "кв. милі (ми²)",
            "sq yard (yd²)" to "кв. ярди (ярд²)",
            "sq foot (ft²)" to "кв. фути (фт²)",
            "acre" to "акри",
            // Volume
            "liter (L)" to "літри (л)",
            "ml" to "мілілітри (мл)",
            "gallon (gal)" to "галони (гал)",
            "cup" to "чашки",
            // Data Storage
            "Bit (b)" to "Біт (б)",
            "Byte (B)" to "Байт (Б)",
            "Kilobit (Kb)" to "Кілобіт (Кб)",
            "Kilobyte (KB)" to "Кілобайт (КБ)",
            "Megabit (Mb)" to "Megabit (Мб)",
            "Megabyte (MB)" to "Megabyte (МБ)",
            "Gigabit (Gb)" to "Гігабіт (Гб)",
            "Gigabyte (GB)" to "Гігабайт (ГБ)",
            "Terabit (Tb)" to "Терабіт (Тб)",
            "Terabyte (TB)" to "Терабайт (ТБ)",
            // Number Systems
            "Decimal" to "Десяткова",
            "Binary" to "Двійкова",
            "Hexadecimal" to "Шістнадцяткова",
            "Octal" to "Восімкова",
            // Time
            "Second (s)" to "Секунда (с)",
            "Minute (min)" to "Хвилина (хв)",
            "Hour (h)" to "Година (год)",
            "Day (d)" to "День (дн)",
            "Week (wk)" to "Тиждень (тиж)",
            "Year (yr)" to "Рік (р)",
            // Speed
            "m/s" to "м/с",
            "km/h" to "км/год",
            "mph" to "миль/год",
            "knots" to "вузли",
            // Pressure
            "Pascal (Pa)" to "Паскаль (Па)",
            "Bar (bar)" to "Бар (бар)",
            "Atmosphere (atm)" to "Атмосфера (атм)",
            "psi" to "psi",
            // Energy
            "Joule (J)" to "Джоуль (Дж)",
            "Kilojoule (kJ)" to "Кілоджоуль (кДж)",
            "Calorie (cal)" to "Калорія (кал)",
            "Kilocalorie (kcal)" to "Кілокалорія (ккал)",
            "Watt-hour (Wh)" to "Ват-година (Вт·год)",
            "Kilowatt-hour (kWh)" to "Кіловат-година (кВт·год)"
        ),
        "be" to mapOf(
            // Length
            "m" to "метры (м)",
            "km" to "кіламетры (км)",
            "cm" to "сантыметры (см)",
            "mm" to "міліметры (мм)",
            "mile" to "мілі (мі)",
            "yard" to "ярды (ярд)",
            "foot" to "футы (фт)",
            "inch" to "цалі (ца)",
            // Temperature
            "Celsius (°C)" to "Градус Цэльсія (°C)",
            "Fahrenheit (°F)" to "Градус Фарэнгейта (°F)",
            "Kelvin (K)" to "Кельвін (K)",
            // Weight
            "kg" to "кілаграмы (кг)",
            "g" to "грамы (г)",
            "mg" to "міліграмы (мг)",
            "µg" to "мікраграмы (мкг)",
            "ton (t)" to "тонны (т)",
            "carat (ct)" to "караты (кар)",
            "lb" to "фунты (фнт)",
            "oz" to "унцыі (унц)",
            "stone (st)" to "стоўны (ст)",
            "grain (gr)" to "граны (гр)",
            // Area
            "sq meter (m²)" to "кв. метры (м²)",
            "sq km (km²)" to "кв. кіламетры (км²)",
            "sq mile (mi²)" to "кв. мілі (мі²)",
            "sq yard (yd²)" to "кв. ярды (ярд²)",
            "sq foot (ft²)" to "кв. футы (фт²)",
            "acre" to "акры",
            // Volume
            "liter (L)" to "літры (л)",
            "ml" to "мілілітры (мл)",
            "gallon (gal)" to "галоны (гал)",
            "cup" to "кубкі",
            // Data Storage
            "Bit (b)" to "Біт (б)",
            "Byte (B)" to "Байт (Б)",
            "Kilobit (Kb)" to "Кілабіт (Кб)",
            "Kilobyte (KB)" to "Кілабайт (КБ)",
            "Megabit (Mb)" to "Megabit (Мб)",
            "Megabyte (MB)" to "Megabyte (МБ)",
            "Gigabit (Gb)" to "Гігабіт (Гб)",
            "Gigabyte (GB)" to "Гігабайт (ГБ)",
            "Terabit (Tb)" to "Тэрабіт (Тб)",
            "Terabyte (TB)" to "Тэрабайт (ТБ)",
            // Number Systems
            "Decimal" to "Дзесятковая",
            "Binary" to "Двойкавая",
            "Hexadecimal" to "Шаснаццаткавая",
            "Octal" to "Васьміковая",
            // Time
            "Second (s)" to "Секунда (с)",
            "Minute (min)" to "Хвіліна (мін)",
            "Hour (h)" to "Гадзіна (г)",
            "Day (d)" to "Дзень (дн)",
            "Week (wk)" to "Тыдзень (тыд)",
            "Year (yr)" to "Год (г)",
            // Speed
            "m/s" to "m/s",
            "km/h" to "км/г",
            "mph" to "миль/г",
            "knots" to "вузлы",
            // Pressure
            "Pascal (Pa)" to "Паскаль (Па)",
            "Bar (bar)" to "Бар (бар)",
            "Atmosphere (atm)" to "Атмасфера (атм)",
            "psi" to "psi",
            // Energy
            "Joule (J)" to "Джоуль (Дж)",
            "Kilojoule (kJ)" to "Кіладжоўль (кДж)",
            "Calorie (cal)" to "Калорыя (кал)",
            "Kilocalorie (kcal)" to "Кілакалорыя (ккал)",
            "Watt-hour (Wh)" to "Ват-гадзіна (Вт·г)",
            "Kilowatt-hour (kWh)" to "Кілават-гадзіна (кВт·г)"
        ),
        "kk" to mapOf(
            // Length
            "m" to "метр (м)",
            "km" to "километр (км)",
            "cm" to "сантиметр (см)",
            "mm" to "миллиметр (мм)",
            "mile" to "миля (ми)",
            "yard" to "ярд (ярд)",
            "foot" to "фут (фут)",
            "inch" to "дюйм (дй)",
            // Temperature
            "Celsius (°C)" to "Цельсий градусы (°C)",
            "Fahrenheit (°F)" to "Фаренгейт градусы (°F)",
            "Kelvin (K)" to "Кельвин (K)",
            // Weight
            "kg" to "килограмм (кг)",
            "g" to "грамм (г)",
            "mg" to "миллиграмм (мг)",
            "µg" to "микрограмм (мкг)",
            "ton (t)" to "тонна (т)",
            "carat (ct)" to "карат (кар)",
            "lb" to "фунт (фунт)",
            "oz" to "унция (унц)",
            "stone (st)" to "стоун (ст)",
            "grain (gr)" to "гран (гр)",
            // Area
            "sq meter (m²)" to "кв. метр (м²)",
            "sq km (km²)" to "кв. километр (км²)",
            "sq mile (mi²)" to "кв. миля (ми²)",
            "sq yard (yd²)" to "кв. ярд (ярд²)",
            "sq foot (ft²)" to "кв. фут (фт²)",
            "acre" to "акр",
            // Volume
            "liter (L)" to "литр (л)",
            "ml" to "миллилитр (мл)",
            "gallon (gal)" to "галлон (гал)",
            "cup" to "шыны",
            // Data Storage
            "Bit (b)" to "Бит (б)",
            "Byte (B)" to "Байт (Б)",
            "Kilobit (Kb)" to "Килобит (Кб)",
            "Kilobyte (KB)" to "Килобайт (КБ)",
            "Megabit (Mb)" to "Megabit (Мб)",
            "Megabyte (MB)" to "Megabyte (МБ)",
            "Gigabit (Gb)" to "Гигабит (Гб)",
            "Gigabyte (GB)" to "Гигабайт (ГБ)",
            "Terabit (Tb)" to "Терабит (Тб)",
            "Terabyte (TB)" to "Терабайт (ТБ)",
            // Number Systems
            "Decimal" to "Ондық",
            "Binary" to "Екілік",
            "Hexadecimal" to "Он алтылық",
            "Octal" to "Сегіздік",
            // Time
            "Second (s)" to "Секунд (с)",
            "Minute (min)" to "Минут (мин)",
            "Hour (h)" to "Сағат (сағ)",
            "Day (d)" to "Күн (күн)",
            "Week (wk)" to "Апта (апт)",
            "Year (yr)" to "Жыл (ж)",
            // Speed
            "m/s" to "м/с",
            "km/h" to "км/сағ",
            "mph" to "миля/сағ",
            "knots" to "торап",
            // Pressure
            "Pascal (Pa)" to "Паскаль (Па)",
            "Bar (bar)" to "Бар (бар)",
            "Atmosphere (atm)" to "Атмосфера (атм)",
            "psi" to "psi",
            // Energy
            "Joule (J)" to "Джоуль (Дж)",
            "Kilojoule (kJ)" to "Килоджоуль (кДж)",
            "Calorie (cal)" to "Калория (кал)",
            "Kilocalorie (kcal)" to "Килокалория (ккал)",
            "Watt-hour (Wh)" to "Ватт-сағат (Вт·сағ)",
            "Kilowatt-hour (kWh)" to "Киловатт-сағат (кВт·сағ)"
        ),
        "es" to mapOf(
            // Length
            "m" to "metros (m)",
            "km" to "kilómetros (km)",
            "cm" to "centímetros (cm)",
            "mm" to "milímetros (mm)",
            "mile" to "millas (mi)",
            "yard" to "yardas (yd)",
            "foot" to "pies (ft)",
            "inch" to "pulgadas (in)",
            // Temperature
            "Celsius (°C)" to "Grado Celsius (°C)",
            "Fahrenheit (°F)" to "Grado Fahrenheit (°F)",
            "Kelvin (K)" to "Kelvin (K)",
            // Weight
            "kg" to "kilogramos (kg)",
            "g" to "gramos (g)",
            "mg" to "miligramos (mg)",
            "µg" to "microgramos (µg)",
            "ton (t)" to "toneladas (t)",
            "carat (ct)" to "quilates (ct)",
            "lb" to "libras (lb)",
            "oz" to "onzas (oz)",
            "stone (st)" to "piedras (st)",
            "grain (gr)" to "granos (gr)",
            // Area
            "sq meter (m²)" to "metros cuad. (m²)",
            "sq km (km²)" to "kilómetros cuad. (km²)",
            "sq mile (mi²)" to "millas cuad. (mi²)",
            "sq yard (yd²)" to "yardas cuad. (yd²)",
            "sq foot (ft²)" to "pies cuad. (ft²)",
            "acre" to "acres",
            // Volume
            "liter (L)" to "litros (L)",
            "ml" to "mililitros (ml)",
            "gallon (gal)" to "galones (gal)",
            "cup" to "tazas",
            // Data Storage
            "Bit (b)" to "Bit (b)",
            "Byte (B)" to "Byte (B)",
            "Kilobit (Kb)" to "Kilobit (Kb)",
            "Kilobyte (KB)" to "Kilobyte (KB)",
            "Megabit (Mb)" to "Megabit (Mb)",
            "Megabyte (MB)" to "Megabyte (MB)",
            "Gigabit (Gb)" to "Gigabit (Gb)",
            "Gigabyte (GB)" to "Gigabyte (GB)",
            "Terabit (Tb)" to "Terabit (Tb)",
            "Terabyte (TB)" to "Terabyte (TB)",
            // Number Systems
            "Decimal" to "Decimal",
            "Binary" to "Binario",
            "Hexadecimal" to "Hexadecimal",
            "Octal" to "Octal",
            // Time
            "Second (s)" to "Segundo (s)",
            "Minute (min)" to "Minuto (min)",
            "Hour (h)" to "Hora (h)",
            "Day (d)" to "Día (d)",
            "Week (wk)" to "Semana (sem)",
            "Year (yr)" to "Año (a)",
            // Speed
            "m/s" to "m/s",
            "km/h" to "km/h",
            "mph" to "mph",
            "knots" to "nudos",
            // Pressure
            "Pascal (Pa)" to "Pascal (Pa)",
            "Bar (bar)" to "Bar (bar)",
            "Atmosphere (atm)" to "Atmósfera (atm)",
            "psi" to "psi",
            // Energy
            "Joule (J)" to "Julio (J)",
            "Kilojoule (kJ)" to "Kilovulio (kJ)",
            "Calorie (cal)" to "Caloría (cal)",
            "Kilocalorie (kcal)" to "Kilocaloría (kcal)",
            "Watt-hour (Wh)" to "Vatio-hora (Wh)",
            "Kilowatt-hour (kWh)" to "Kilovatio-hora (kWh)"
        ),
        "pl" to mapOf(
            // Length
            "m" to "metry (m)",
            "km" to "kilometry (km)",
            "cm" to "centymetry (cm)",
            "mm" to "milimetry (mm)",
            "mile" to "mile (mi)",
            "yard" to "yardy (yd)",
            "foot" to "stopy (ft)",
            "inch" to "cale (in)",
            // Temperature
            "Celsius (°C)" to "Stopień Celsjusza (°C)",
            "Fahrenheit (°F)" to "Stopień Fahrenheita (°F)",
            "Kelvin (K)" to "Kelwin (K)",
            // Weight
            "kg" to "kilogramy (kg)",
            "g" to "gramy (g)",
            "mg" to "miligramy (mg)",
            "µg" to "mikrogramy (µg)",
            "ton (t)" to "tony (t)",
            "carat (ct)" to "karaty (ct)",
            "lb" to "funty (lb)",
            "oz" to "uncje (oz)",
            "stone (st)" to "kamienie (st)",
            "grain (gr)" to "grany (gr)",
            // Area
            "sq meter (m²)" to "m²",
            "sq km (km²)" to "km²",
            "sq mile (mi²)" to "mile kwadratowe (mi²)",
            "sq yard (yd²)" to "yardy kwadratowe (yd²)",
            "sq foot (ft²)" to "stopy kwadratowe (ft²)",
            "acre" to "akry",
            // Volume
            "liter (L)" to "litry (L)",
            "ml" to "mililitry (ml)",
            "gallon (gal)" to "galony (gal)",
            "cup" to "szklanki",
            // Data Storage
            "Bit (b)" to "Bit (b)",
            "Byte (B)" to "Bajt (B)",
            "Kilobit (Kb)" to "Kilobit (Kb)",
            "Kilobyte (KB)" to "Kilobajt (KB)",
            "Megabit (Mb)" to "Megabit (Mb)",
            "Megabyte (MB)" to "Megabajt (MB)",
            "Gigabit (Gb)" to "Gigabit (Gb)",
            "Gigabyte (GB)" to "Gigabajt (GB)",
            "Terabit (Tb)" to "Terabit (Tb)",
            "Terabyte (TB)" to "Terabajt (TB)",
            // Number Systems
            "Decimal" to "Dziesiętny",
            "Binary" to "Binarny",
            "Hexadecimal" to "Szesnastkowy",
            "Octal" to "Ósemkowy",
            // Time
            "Second (s)" to "Sekunda (s)",
            "Minute (min)" to "Minuta (min)",
            "Hour (h)" to "Godzina (h)",
            "Day (d)" to "Dzień (d)",
            "Week (wk)" to "Tydzień (tyg)",
            "Year (yr)" to "Rok (r)",
            // Speed
            "m/s" to "m/s",
            "km/h" to "km/h",
            "mph" to "mph",
            "knots" to "węzły",
            // Pressure
            "Pascal (Pa)" to "Pascal (Pa)",
            "Bar (bar)" to "Bar (bar)",
            "Atmosphere (atm)" to "Atmosfera (atm)",
            "psi" to "psi",
            // Energy
            "Joule (J)" to "Dżul (J)",
            "Kilojoule (kJ)" to "Kilodżul (kJ)",
            "Calorie (cal)" to "Kaloria (cal)",
            "Kilocalorie (kcal)" to "Kilokaloria (kcal)",
            "Watt-hour (Wh)" to "Watogodzina (Wh)",
            "Kilowatt-hour (kWh)" to "Kilowatogodzina (kWh)"
        ),
        "de" to mapOf(
            // Length
            "m" to "Meter (m)",
            "km" to "Kilometer (km)",
            "cm" to "Zentimeter (cm)",
            "mm" to "Millimeter (mm)",
            "mile" to "Meilen (mi)",
            "yard" to "Yards (yd)",
            "foot" to "Fuß (ft)",
            "inch" to "Zoll (in)",
            // Temperature
            "Celsius (°C)" to "Grad Celsius (°C)",
            "Fahrenheit (°F)" to "Grad Fahrenheit (°F)",
            "Kelvin (K)" to "Kelvin (K)",
            // Weight
            "kg" to "Kilogramm (kg)",
            "g" to "Gramm (g)",
            "mg" to "Milligramm (mg)",
            "µg" to "Mikrogramm (µg)",
            "ton (t)" to "Tonnen (t)",
            "carat (ct)" to "Karat (ct)",
            "lb" to "Pfund (lb)",
            "oz" to "Unzen (oz)",
            "stone (st)" to "Stones (st)",
            "grain (gr)" to "Grains (gr)",
            // Area
            "sq meter (m²)" to "Quadratmeter (m²)",
            "sq km (km²)" to "Quadratkilometer (km²)",
            "sq mile (mi²)" to "Quadratmeilen (mi²)",
            "sq yard (yd²)" to "Quadratyards (yd²)",
            "sq foot (ft²)" to "Quadratfuß (ft²)",
            "acre" to "Acker/Acres",
            // Volume
            "liter (L)" to "Liter (L)",
            "ml" to "Milliliter (ml)",
            "gallon (gal)" to "Gallonen (gal)",
            "cup" to "Tassen",
            // Data Storage
            "Bit (b)" to "Bit (b)",
            "Byte (B)" to "Byte (B)",
            "Kilobit (Kb)" to "Kilobit (Kb)",
            "Kilobyte (KB)" to "Kilobyte (KB)",
            "Megabit (Mb)" to "Megabit (Mb)",
            "Megabyte (MB)" to "Megabyte (MB)",
            "Gigabit (Gb)" to "Gigabit (Gb)",
            "Gigabyte (GB)" to "Gigabyte (GB)",
            "Terabit (Tb)" to "Terabit (Tb)",
            "Terabyte (TB)" to "Terabyte (TB)",
            // Number Systems
            "Decimal" to "Dezimal",
            "Binary" to "Binär",
            "Hexadecimal" to "Hexadezimal",
            "Octal" to "Oktal",
            // Time
            "Second (s)" to "Sekunde (s)",
            "Minute (min)" to "Minute (min)",
            "Hour (h)" to "Stunde (h)",
            "Day (d)" to "Tag (d)",
            "Week (wk)" to "Woche (wo)",
            "Year (yr)" to "Jahr (j)",
            // Speed
            "m/s" to "m/s",
            "km/h" to "km/h",
            "mph" to "mph",
            "knots" to "Knoten",
            // Pressure
            "Pascal (Pa)" to "Pascal (Pa)",
            "Bar (bar)" to "Bar (bar)",
            "Atmosphere (atm)" to "Atmosphäre (atm)",
            "psi" to "psi",
            // Energy
            "Joule (J)" to "Joule (J)",
            "Kilojoule (kJ)" to "Kilojoule (kJ)",
            "Calorie (cal)" to "Calorie (cal)",
            "Kilocalorie (kcal)" to "Kilocalorie (kcal)",
            "Watt-hour (Wh)" to "Wattstunde (Wh)",
            "Kilowatt-hour (kWh)" to "Kilowattstunde (kWh)"
        )
    )

    fun translate(key: String, langCode: String): String {
        val langMap = translations[langCode] ?: translations["en"]!!
        return langMap[key] ?: translations["en"]!![key] ?: key
    }

    fun translateUnit(unitKey: String, langCode: String): String {
        val langMap = unitTranslations[langCode] ?: unitTranslations["en"]!!
        return langMap[unitKey] ?: unitTranslations["en"]!![unitKey] ?: unitKey
    }
}
