name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Удаляем старую кривую папку gradle и генерируем чистый Wrapper с нуля
      - name: Generate Fresh Gradle Wrapper
        run: |
          rm -rf gradle/wrapper
          gradle wrapper --gradle-version 8.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK (release)
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          
